name: Create Release on Tag

on:
    push:
        tags:
            - "*"

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read

        steps:
            - uses: actions/checkout@v4

            - name: Create Zip file
              run: |
                  cd java && zip -r ../minecraft_java.zip . -x ".*" && cd ..
                  cd bedrock && zip -r ../minecraft_bedrock.zip . -x ".*" && cd ..

            - name: Rename Zips
              run: |
                  mv minecraft_java.zip CyberEnte-ResourcePack-Java.zip
                  mv minecraft_bedrock.zip CyberEnte-ResourcePack-Bedrock.mcpack

            - name: Archive Release Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: minecraft_packs
                  path: |
                      CyberEnte-ResourcePack-Java.zip
                      CyberEnte-ResourcePack-Bedrock.mcpack

    release:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Download Release Artifacts
              uses: actions/download-artifact@v4
              with:
                  name: minecraft_packs
                  path: packs

            - name: Compute SHA1 of Java Zip
              id: sha
              run: |
                  sha1=$(sha1sum "packs/CyberEnte-ResourcePack-Java.zip" | awk '{ print $1 }')
                  echo "sha1=$sha1" >> $GITHUB_OUTPUT

            - name: Create Release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ github.ref_name }}
                  name: Release ${{ github.ref_name }}
                  draft: false
                  prerelease: false
                  files: |
                      packs/CyberEnte-ResourcePack-Java.zip
                      packs/CyberEnte-ResourcePack-Bedrock.mcpack
                  body: |
                      This is an automatically generated release.

                      **CyberEnte-ResourcePack-Java.zip SHA-1:** `${{ steps.sha.outputs.sha1 }}`

                      _Generated by GitHub Actions._
