name: Create Release on Tag

on:
    push:
        tags:
            - "*"

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read

        steps:
            - uses: actions/checkout@v4

            - name: Create Zip file
              run: |
                  zip -r minecraft_assets.zip . --exclude=.* --exclude=minecraft_assets.zip

            - name: Rename ZIP with tag name
              run: |
                  mv minecraft_assets.zip CyberEnte-ResourcePack.zip

            - name: Archive Release Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: minecraft_assets
                  path: CyberEnte-ResourcePack.zip

    release:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Download Release Artifacts
              uses: actions/download-artifact@v4
              with:
                  name: minecraft_assets
                  path: assets

            - name: Create Release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ github.ref_name }}
                  name: Release v${{ github.ref_name }}
                  draft: false
                  prerelease: false
                  files: assets/CyberEnte-ResourcePack.zip
                  body: |
                      This is an automatically generated release.

                      _Generated by GitHub Actions._
